{{- if .Values.qbittorrent.config.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent.configPersistenceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.config.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.qbittorrent.config.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.qbittorrent.config.persistence.volumeName }}
  volumeName: {{ .Values.qbittorrent.config.persistence.volumeName }}
  {{- end }}
  {{- with .Values.qbittorrent.config.persistence.storageClass }}
  storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.qbittorrent.config.persistence.size }}"
{{- end }}
