{{- if .Values.qbittorrent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qbittorrent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.qbittorrent.serviceAccount.automount }}
{{- end }}
