apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.service.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.qbittorrent.service.web.type }}
  ports:
    - port: {{ .Values.qbittorrent.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
