{{- if and .Values.genericDevicePlugin.enabled .Values.genericDevicePlugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "genericDevicePlugin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genericDevicePlugin.labels" . | nindent 4 }}
  {{- with .Values.genericDevicePlugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.genericDevicePlugin.serviceAccount.automount }}
{{- end }}
