{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "3d-printing-cost-calculators.serviceAccountName" . }}
  labels:
    {{- include "3d-printing-cost-calculators.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default true .Values.serviceAccount.automount }}
{{- end }}
